print('hello')
print('this is also a string')
print("I'm going on a run")
print('hello world one')
print('hello world two')
print('hello \n world')
print('hello \nworld')
print('hello \tworld')
len('hello')
len('I am')