import datetime
t = datetime.time(5,25,1)
print(t)
print(t.hour)
print(t.minute)
print(t.microsecond)
print(t.second)
print(datetime.time.min)
print(datetime.time.max)
print(datetime.time.resolution)

today = datetime.date.today()
print(today)
print(today.timetuple())
print(today.year)
print(today.month)
print(today.day)
print(datetime.date.resolution)

d1 = datetime.date(2015,3,11)
print(d1)
d2 = d1.replace(year=1990)
print(d2)
print(d1-d2)